mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_
  mapper-locations: classpath*:/mapper/**/*.xml


server:
  port: 8888
spring:
  application:
    name: icatw-blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345
    url: jdbc:mysql://localhost:3306/ry-vue-blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  mvc:
    servlet:
      path:
aliyun:
  oss:
    end-point: oss-cn-beijing.aliyuncs.com
    key-id: LTAI5t9s2XYyATR2g2iNy3TZ
    key-secret: DZppauve3NQpvZr6oalsvM9DmKEpOH
    bucket-name: blog-icatwms
