mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_
  mapper-locations: classpath*:/mapper/**/*.xml
server:
  port: 8888
spring:
  application:
    name: icatw-blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345
    url: jdbc:mysql://localhost:3306/icatw_blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
  redis:
    host: #
    port: 6379
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
aliyun:
  oss:
    end-point: #
    key-id: #
    key-secret: #
    bucket-name: #
